kafka:
  bootstrapAddress: kafka:9092
  topics:
    tweets-message-topic: tweets-message-topic
server:
  port: 8080
logging:
  file:
    path: .
hbc-client:
  api-key: "jDjdWMpNLlUWsnOjPNSUrl4ab"
  api-secret: "7mGTiF21kqoxQgNEwFwewPzpVnlTRkuOGE1jaKYBON6tL1rakD"
  access-token: "926121108843257857-up8xjm9lexCQeakRnSWyfWDtEHndKex"
  access-token-secret: "yftVlTAbT48EnxNZeIkar4GeBN1sgvkiEXyZWgWiEP7gb"